bot:
  name: ${BOT_NAME}
  key: ${BOT_KEY}
  uri: ${BOT_URI}

server:
  ssl:
    enabled: false
  port : 8080
ru:
  wallentos:
    car-calculator:
      log-spreedsheed-id: ${LOG_SPREEDSHEED_ID}
      admin-id: 126866786
      extra-pay-corea:
        krw: 2500000
        rub: 70000
      extra-pay-china:
        cny: 2500000
        rub: 70000
      exchange-api:
        host-cbr: https://www.cbr-xml-daily.ru/daily_json.js
        host-naver: https://finance.naver.com/marketindex/exchangeDetail.nhn?marketindexCd=FX_USDKRW
      

